package constant

const (
	FOOTBALL_MALE_JR      = "FOOTBALL_MALE_JR"
	FOOTBALL_MALE_SR      = "FOOTBALL_MALE_SR"
	BASKETBALL_MALE_JR    = "BASKETBALL_MALE_JR"
	BASKETBALL_MALE_SR    = "BASKETBALL_MALE_SR"
	BASKETBALL_FEMALE_ALL = "BASKETBALL_FEMALE_ALL"
	VOLLEYBALL_MALE_ALL   = "VOLLEYBALL_MALE_ALL"
	VOLLEYBALL_FEMALE_ALL = "VOLLEYBALL_FEMALE_ALL"
	CHAIRBALL_FEMALE_ALL  = "CHAIRBALL_FEMALE_ALL"
	RUNNING               = "RUNNING"
	TUG_OF_WAR            = "TUG_OF_WAR"
	TRADITIONAL_SPORTS    = "TRADITIONAL_SPORTS"
	TUG_OF_WAR_CHAK_YOR   = "TUG_OF_WAR_CHAK_YOR"
	RUNNING_PIAW          = "RUNNING_PIAW"
)
